#include "FXOT.h"
#include "FXBoostPrivate.h"

namespace {
    FXString
    findTagName(const FXMap<FXString, FXString> & map, FXTag tag, bool tagIsKey) {
        FXString str = BST::trim(FXTag2Str(tag));
        if (tagIsKey) {
            auto itr = map.find(str);
            if (itr != map.end())
                return itr->second;
        }
        else {
            for (const auto & p: map) 
                if (p.second == str)
                    return p.first;
        }
        return "";
    }
}

namespace FXOT {
    const FXTag DEFAULT_SCRIPT = 'DLFT';
    const FXTag DEFAULT_LANGUAGE = 'dlft';
    const FXTag MERGED_GSUBGPOS = 'GSGP';
    
    const unsigned int DEFAULT_LANGUAGE_INDEX = 0xFFFFu;
    
    FXString
    scriptName(FXTag script) {
        static FXMap<FXString, FXString> map = {
            {"Arabic", "arab"},
            {"Armenian", "armn"},
            {"Avestan", "avst"},
            {"Balinese", "bali"},
            {"Bamum", "bamu"},
            {"Batak", "batk"},
            {"Bengali", "beng"},
            {"Bengali v.2", "bng2"},
            {"Bopomofo", "bopo"},
            {"Braille", "brai"},
            {"Brahmi", "brah"},
            {"Buginese", "bugi"},
            {"Buhid", "buhd"},
            {"Byzantine Music", "byzm"},
            {"Canadian Syllabics", "cans"},
            {"Carian", "cari"},
            {"Chakma", "cakm"},
            {"Cham", "cham"},
            {"Cherokee", "cher"},
            {"CJK Ideographic", "hani"},
            {"Coptic", "copt"},
            {"Cypriot Syllabary", "cprt"},
            {"Cyrillic", "cyrl"},
            {"Default", "DFLT"},
            {"Deseret", "dsrt"},
            {"Devanagari", "deva"},
            {"Devanagari v.2", "dev2"},
            {"Egyptian heiroglyphs", "egyp"},
            {"Ethiopic", "ethi"},
            {"Georgian", "geor"},
            {"Glagolitic", "glag"},
            {"Gothic", "goth"},
            {"Greek", "grek"},
            {"Gujarati", "gujr"},
            {"Gujarati v.2", "gjr2"},
            {"Gurmukhi", "guru"},
            {"Gurmukhi v.2", "gur2"},
            {"Hangul", "hang"},
            {"Hangul Jamo", "jamo"},
            {"Hanunoo", "hano"},
            {"Hebrew", "hebr"},
            {"Hiragana", "kana"},
            {"Imperial Aramaic", "armi"},
            {"Inscriptional Pahlavi", "phli"},
            {"Inscriptional Parthian", "prti"},
            {"Javanese", "java"},
            {"Kaithi", "kthi"},
            {"Kannada", "knda"},
            {"Kannada v.2", "knd2"},
            {"Katakana", "kana"},
            {"Kayah Li", "kali"},
            {"Kharosthi", "khar"},
            {"Khmer", "khmr"},
            {"Lao", "lao"},
            {"Latin", "latn"},
            {"Lepcha", "lepc"},
            {"Limbu", "limb"},
            {"Linear B", "linb"},
            {"Lisu (Fraser)", "lisu"},
            {"Lycian", "lyci"},
            {"Lydian", "lydi"},
            {"Malayalam", "mlym"},
            {"Malayalam v.2", "mlm2"},
            {"Mandaic, Mandaean", "mand"},
            {"Mathematical Alphanumeric Symbols", "math"},
            {"Meitei Mayek (Meithei, Meetei)", "mtei"},
            {"Meroitic Cursive", "merc"},
            {"Meroitic Hieroglyphs", "mero"},
            {"Mongolian", "mong"},
            {"Musical Symbols", "musc"},
            {"Myanmar", "mymr"},
            {"New Tai Lue", "talu"},
            {"N'Ko", "nko"},
            {"Ogham", "ogam"},
            {"Ol Chiki", "olck"},
            {"Old Italic", "ital"},
            {"Old Persian Cuneiform", "xpeo"},
            {"Old South Arabian", "sarb"},
            {"Old Turkic, Orkhon Runic", "orkh"},
            {"Odia (formerly Oriya)", "orya"},
            {"Odia v.2 (formerly Oriya v.2)", "ory2"},
            {"Osmanya", "osma"},
            {"Phags-pa", "phag"},
            {"Phoenician", "phnx"},
            {"Rejang", "rjng"},
            {"Runic", "runr"},
            {"Samaritan", "samr"},
            {"Saurashtra", "saur"},
            {"Sharada", "shrd"},
            {"Shavian", "shaw"},
            {"Sinhala", "sinh"},
            {"Sora Sompeng", "sora"},
            {"Sumero-Akkadian Cuneiform", "xsux"},
            {"Sundanese", "sund"},
            {"Syloti Nagri", "sylo"},
            {"Syriac", "syrc"},
            {"Tagalog", "tglg"},
            {"Tagbanwa", "tagb"},
            {"Tai Le", "tale"},
            {"Tai Tham (Lanna)", "lana"},
            {"Tai Viet", "tavt"},
            {"Takri", "takr"},
            {"Tamil", "taml"},
            {"Tamil v.2", "tml2"},
            {"Telugu", "telu"},
            {"Telugu v.2", "tel2"},
            {"Thaana", "thaa"},
            {"Thai", "thai"},
            {"Tibetan", "tibt"},
            {"Tifinagh", "tfng"},
            {"Ugaritic Cuneiform", "ugar"},
            {"Vai", "vai"},
            {"Yi", "yi"},
        };

        return findTagName(map, script, false);
    }
    
    FXString
    languageName(FXTag language) {
        static FXMap<FXString, FXString> map = {
            {"Abaza", "ABA"},
            {"Abkhazian", "ABK"},
            {"Adyghe", "ADY"},
            {"Afrikaans", "AFK"},
            {"Afar", "AFR"},
            {"Agaw", "AGW"},
            {"Alsatian", "ALS"},
            {"Altai", "ALT"},
            {"Amharic", "AMH"},
            {"Phonetic transcription—Americanist conventions", "APPH"},
            {"Arabic", "ARA"},
            {"Aari", "ARI"},
            {"Arakanese", "ARK"},
            {"Assamese", "ASM"},
            {"Athapaskan", "ATH"},
            {"Avar", "AVR"},
            {"Awadhi", "AWA"},
            {"Aymara", "AYM"},
            {"Azeri", "AZE"},
            {"Badaga", "BAD"},
            {"Baghelkhandi", "BAG"},
            {"Balkar", "BAL"},
            {"Baule", "BAU"},
            {"Berber", "BBR"},
            {"Bench", "BCH"},
            {"Bible Cree", "BCR"},
            {"Belarussian", "BEL"},
            {"Bemba", "BEM"},
            {"Bengali", "BEN"},
            {"Bulgarian", "BGR"},
            {"Bhili", "BHI"},
            {"Bhojpuri", "BHO"},
            {"Bikol", "BIK"},
            {"Bilen", "BIL"},
            {"Blackfoot", "BKF"},
            {"Balochi", "BLI"},
            {"Balante", "BLN"},
            {"Balti", "BLT"},
            {"Bambara", "BMB"},
            {"Bamileke", "BML"},
            {"Bosnian", "BOS"},
            {"Breton", "BRE"},
            {"Brahui", "BRH"},
            {"Braj Bhasha", "BRI"},
            {"Burmese", "BRM"},
            {"Bashkir", "BSH"},
            {"Beti", "BTI"},
            {"Catalan", "CAT"},
            {"Cebuano", "CEB"},
            {"Chechen", "CHE"},
            {"Chaha Gurage", "CHG"},
            {"Chattisgarhi", "CHH"},
            {"Chichewa", "CHI"},
            {"Chukchi", "CHK"},
            {"Chipewyan", "CHP"},
            {"Cherokee", "CHR"},
            {"Chuvash", "CHU"},
            {"Comorian", "CMR"},
            {"Coptic", "COP"},
            {"Corsican", "COS"},
            {"Cree", "CRE"},
            {"Carrier", "CRR"},
            {"Crimean Tatar", "CRT"},
            {"Church Slavonic", "CSL"},
            {"Czech", "CSY"},
            {"Danish", "DAN"},
            {"Dargwa", "DAR"},
            {"Woods Cree", "DCR"},
            {"German", "DEU"},
            {"Default", "dlft"},
            {"Dogri", "DGR"},
            {"Dhivehi", "DHV (deprecated)"},
            {"Dhivehi", "DIV"},
            {"Djerma", "DJR"},
            {"Dangme", "DNG"},
            {"Dinka", "DNK"},
            {"Dari", "DRI"},
            {"Dungan", "DUN"},
            {"Dzongkha", "DZN"},
            {"Ebira", "EBI"},
            {"Eastern Cree", "ECR"},
            {"Edo", "EDO"},
            {"Efik", "EFI"},
            {"Greek", "ELL"},
            {"English", "ENG"},
            {"Erzya", "ERZ"},
            {"Spanish", "ESP"},
            {"Estonian", "ETI"},
            {"Basque", "EUQ"},
            {"Evenki", "EVK"},
            {"Even", "EVN"},
            {"Ewe", "EWE"},
            {"French Antillean", "FAN"},
            {"Farsi", "FAR"},
            {"Finnish", "FIN"},
            {"Fijian", "FJI"},
            {"Flemish", "FLE"},
            {"Forest Nenets", "FNE"},
            {"Fon", "FON"},
            {"Faroese", "FOS"},
            {"French", "FRA"},
            {"Frisian", "FRI"},
            {"Friulian", "FRL"},
            {"Futa", "FTA"},
            {"Fulani", "FUL"},
            {"Ga", "GAD"},
            {"Gaelic", "GAE"},
            {"Gagauz", "GAG"},
            {"Galician", "GAL"},
            {"Garshuni", "GAR"},
            {"Garhwali", "GAW"},
            {"Ge'ez", "GEZ"},
            {"Gilyak", "GIL"},
            {"Gumuz", "GMZ"},
            {"Gondi", "GON"},
            {"Greenlandic", "GRN"},
            {"Garo", "GRO"},
            {"Guarani", "GUA"},
            {"Gujarati", "GUJ"},
            {"Haitian", "HAI"},
            {"Halam", "HAL"},
            {"Harauti", "HAR"},
            {"Hausa", "HAU"},
            {"Hawaiin", "HAW"},
            {"Hammer-Banna", "HBN"},
            {"Hiligaynon", "HIL"},
            {"Hindi", "HIN"},
            {"High Mari", "HMA"},
            {"Hindko", "HND"},
            {"Ho", "HO"},
            {"Harari", "HRI"},
            {"Croatian", "HRV"},
            {"Hungarian", "HUN"},
            {"Armenian", "HYE"},
            {"Igbo", "IBO"},
            {"Ijo", "IJO"},
            {"Ilokano", "ILO"},
            {"Indonesian", "IND"},
            {"Ingush", "ING"},
            {"Inuktitut", "INU"},
            {"Phonetic transcription—IPA conventions", "IPPH"},
            {"Irish", "IRI"},
            {"Irish Traditional", "IRT"},
            {"Icelandic", "ISL"},
            {"Inari Sami", "ISM"},
            {"Italian", "ITA"},
            {"Hebrew", "IWR"},
            {"Javanese", "JAV"},
            {"Yiddish", "JII"},
            {"Japanese", "JAN"},
            {"Judezmo", "JUD"},
            {"Jula", "JUL"},
            {"Kabardian", "KAB"},
            {"Kachchi", "KAC"},
            {"Kalenjin", "KAL"},
            {"Kannada", "KAN"},
            {"Karachay", "KAR"},
            {"Georgian", "KAT"},
            {"Kazakh", "KAZ"},
            {"Kebena", "KEB"},
            {"Khutsuri Georgian", "KGE"},
            {"Khakass", "KHA"},
            {"Khanty-Kazim", "KHK"},
            {"Khmer", "KHM"},
            {"Khanty-Shurishkar", "KHS"},
            {"Khanty-Vakhi", "KHV"},
            {"Khowar", "KHW"},
            {"Kikuyu", "KIK"},
            {"Kirghiz", "KIR"},
            {"Kisii", "KIS"},
            {"Kokni", "KKN"},
            {"Kalmyk", "KLM"},
            {"Kamba", "KMB"},
            {"Kumaoni", "KMN"},
            {"Komo", "KMO"},
            {"Komso", "KMS"},
            {"Kanuri", "KNR"},
            {"Kodagu", "KOD"},
            {"Korean Old Hangul", "KOH"},
            {"Konkani", "KOK"},
            {"Kikongo", "KON"},
            {"Komi-Permyak", "KOP"},
            {"Korean", "KOR"},
            {"Komi-Zyrian", "KOZ"},
            {"Kpelle", "KPL"},
            {"Krio", "KRI"},
            {"Karakalpak", "KRK"},
            {"Karelian", "KRL"},
            {"Karaim", "KRM"},
            {"Karen", "KRN"},
            {"Koorete", "KRT"},
            {"Kashmiri", "KSH"},
            {"Khasi", "KSI"},
            {"Kildin Sami", "KSM"},
            {"Kui", "KUI"},
            {"Kulvi", "KUL"},
            {"Kumyk", "KUM"},
            {"Kurdish", "KUR"},
            {"Kurukh", "KUU"},
            {"Kuy", "KUY"},
            {"Koryak", "KYK"},
            {"Ladin", "LAD"},
            {"Lahuli", "LAH"},
            {"Lak", "LAK"},
            {"Lambani", "LAM"},
            {"Lao", "LAO"},
            {"Latin", "LAT"},
            {"Laz", "LAZ"},
            {"L-Cree", "LCR"},
            {"Ladakhi", "LDK"},
            {"Lezgi", "LEZ"},
            {"Lingala", "LIN"},
            {"Low Mari", "LMA"},
            {"Limbu", "LMB"},
            {"Lomwe", "LMW"},
            {"Lower Sorbian", "LSB"},
            {"Lule Sami", "LSM"},
            {"Lithuanian", "LTH"},
            {"Luxembourgish", "LTZ"},
            {"Luba", "LUB"},
            {"Luganda", "LUG"},
            {"Luhya", "LUH"},
            {"Luo", "LUO"},
            {"Latvian", "LVI"},
            {"Majang", "MAJ"},
            {"Makua", "MAK"},
            {"Malayalam Traditional", "MAL"},
            {"Mansi", "MAN"},
            {"Mapudungun", "MAP"},
            {"Marathi", "MAR"},
            {"Marwari", "MAW"},
            {"Mbundu", "MBN"},
            {"Manchu", "MCH"},
            {"Moose Cree", "MCR"},
            {"Mende", "MDE"},
            {"Me'en", "MEN"},
            {"Mizo", "MIZ"},
            {"Macedonian", "MKD"},
            {"Male", "MLE"},
            {"Malagasy", "MLG"},
            {"Malinke", "MLN"},
            {"Malayalam Reformed", "MLR"},
            {"Malay", "MLY"},
            {"Mandinka", "MND"},
            {"Mongolian", "MNG"},
            {"Manipuri", "MNI"},
            {"Maninka", "MNK"},
            {"Manx Gaelic", "MNX"},
            {"Mohawk", "MOH"},
            {"Moksha", "MOK"},
            {"Moldavian", "MOL"},
            {"Mon", "MON"},
            {"Moroccan", "MOR"},
            {"Maori", "MRI"},
            {"Maithili", "MTH"},
            {"Maltese", "MTS"},
            {"Mundari", "MUN"},
            {"Naga-Assamese", "NAG"},
            {"Nanai", "NAN"},
            {"Naskapi", "NAS"},
            {"N-Cree", "NCR"},
            {"Ndebele", "NDB"},
            {"Ndonga", "NDG"},
            {"Nepali", "NEP"},
            {"Newari", "NEW"},
            {"Nagari", "NGR"},
            {"Norway House Cree", "NHC"},
            {"Nisi", "NIS"},
            {"Niuean", "NIU"},
            {"Nkole", "NKL"},
            {"N'Ko", "NKO"},
            {"Dutch", "NLD"},
            {"Nogai", "NOG"},
            {"Norwegian", "NOR"},
            {"Northern Sami", "NSM"},
            {"Northern Tai", "NTA"},
            {"Esperanto", "NTO"},
            {"Nynorsk", "NYN"},
            {"Occitan", "OCI"},
            {"Oji-Cree", "OCR"},
            {"Ojibway", "OJB"},
            {"Odia(formerly Oriya)", "ORI"},
            {"Oromo", "ORO"},
            {"Ossetian", "OSS"},
            {"Palestinian Aramaic", "PAA"},
            {"Pali", "PAL"},
            {"Punjabi", "PAN"},
            {"Palpa", "PAP"},
            {"Pashto", "PAS"},
            {"Polytonic Greek", "PGR"},
            {"Filipino", "PIL"},
            {"Palaung", "PLG"},
            {"Polish", "PLK"},
            {"Provencal", "PRO"},
            {"Portuguese", "PTG"},
            {"Chin", "QIN"},
            {"Rajasthani", "RAJ"},
            {"R-Cree", "RCR"},
            {"Russian Buriat", "RBU"},
            {"Riang", "RIA"},
            {"Rhaeto-Romanic", "RMS"},
            {"Romanian", "ROM"},
            {"Romany", "ROY"},
            {"Rusyn", "RSY"},
            {"Ruanda", "RUA"},
            {"Russian", "RUS"},
            {"Sadri", "SAD"},
            {"Sanskrit", "SAN"},
            {"Santali", "SAT"},
            {"Sayisi", "SAY"},
            {"Sekota", "SEK"},
            {"Selkup", "SEL"},
            {"Sango", "SGO"},
            {"Shan", "SHN"},
            {"Sibe", "SIB"},
            {"Sidamo", "SID"},
            {"Silte Gurage", "SIG"},
            {"Skolt Sami", "SKS"},
            {"Slovak", "SKY"},
            {"Slavey", "SLA"},
            {"Slovenian", "SLV"},
            {"Somali", "SML"},
            {"Samoan", "SMO"},
            {"Sena", "SNA"},
            {"Sindhi", "SND"},
            {"Sinhalese", "SNH"},
            {"Soninke", "SNK"},
            {"Sodo Gurage", "SOG"},
            {"Sotho", "SOT"},
            {"Albanian", "SQI"},
            {"Serbian", "SRB"},
            {"Saraiki", "SRK"},
            {"Serer", "SRR"},
            {"South Slavey", "SSL"},
            {"Southern Sami", "SSM"},
            {"Suri", "SUR"},
            {"Svan", "SVA"},
            {"Swedish", "SVE"},
            {"Swadaya Aramaic", "SWA"},
            {"Swahili", "SWK"},
            {"Swazi", "SWZ"},
            {"Sutu", "SXT"},
            {"Syriac", "SYR"},
            {"Tabasaran", "TAB"},
            {"Tajiki", "TAJ"},
            {"Tamil", "TAM"},
            {"Tatar", "TAT"},
            {"TH-Cree", "TCR"},
            {"Telugu", "TEL"},
            {"Tongan", "TGN"},
            {"Tigre", "TGR"},
            {"Tigrinya", "TGY"},
            {"Thai", "THA"},
            {"Tahitian", "THT"},
            {"Tibetan", "TIB"},
            {"Turkmen", "TKM"},
            {"Temne", "TMN"},
            {"Tswana", "TNA"},
            {"Tundra Nenets", "TNE"},
            {"Tonga", "TNG"},
            {"Todo", "TOD"},
            {"Turkish", "TRK"},
            {"Tsonga", "TSG"},
            {"Turoyo Aramaic", "TUA"},
            {"Tulu", "TUL"},
            {"Tuvin", "TUV"},
            {"Twi", "TWI"},
            {"Udmurt", "UDM"},
            {"Ukrainian", "UKR"},
            {"Urdu", "URD"},
            {"Upper Sorbian", "USB"},
            {"Uyghur", "UYG"},
            {"Uzbek", "UZB"},
            {"Venda", "VEN"},
            {"Vietnamese", "VIT"},
            {"Wa", "WA"},
            {"Wagdi", "WAG"},
            {"West-Cree", "WCR"},
            {"Welsh", "WEL"},
            {"Wolof", "WLF"},
            {"Tai Lue", "XBD"},
            {"Xhosa", "XHS"},
            {"Yakut", "YAK"},
            {"Yoruba", "YBA"},
            {"Y-Cree", "YCR"},
            {"Yi Classic", "YIC"},
            {"Yi Modern", "YIM"},
            {"Chinese Hong Kong", "ZHH"},
            {"Chinese Phonetic", "ZHP"},
            {"Chinese Simplified", "ZHS"},
            {"Chinese Traditional", "ZHT"},
            {"Zande", "ZND"},
            {"Zulu", "ZUL"},
        };
        return findTagName(map, language, false);
    }
    
    FXString
    featureName(FXTag feature) {
        static FXMap<FXString, FXString> map = {
            {"aalt", "Access All Alternates"},
            {"abvf", "Above-base Forms"},
            {"abvm", "Above-base Mark Positioning"},
            {"abvs", "Above-base Substitutions"},
            {"afrc", "Alternative Fractions"},
            {"akhn", "Akhands"},
            {"blwf", "Below-base Forms"},
            {"blwm", "Below-base Mark Positioning"},
            {"blws", "Below-base Substitutions"},
            {"calt", "Contextual Alternates"},
            {"case", "Case-Sensitive Forms"},
            {"ccmp", "Glyph Composition / Decomposition"},
            {"cfar", "Conjunct Form After Ro"},
            {"cjct", "Conjunct Forms"},
            {"clig", "Contextual Ligatures"},
            {"cpct", "Centered CJK Punctuation"},
            {"cpsp", "Capital Spacing"},
            {"cswh", "Contextual Swash"},
            {"curs", "Cursive Positioning"},
            {"cv01-cv99", "Character Variants"},
            {"c2pc", "Petite Capitals From Capitals"},
            {"c2sc", "Small Capitals From Capitals"},
            {"dist", "Distances"},
            {"dlig", "Discretionary Ligatures"},
            {"dnom", "Denominators"},
            {"expt", "Expert Forms"},
            {"falt", "Final Glyph on Line Alternates"},
            {"fin2", "Terminal Forms #2"},
            {"fin3", "Terminal Forms #3"},
            {"fina", "Terminal Forms"},
            {"frac", "Fractions"},
            {"fwid", "Full Widths"},
            {"half", "Half Forms"},
            {"haln", "Halant Forms"},
            {"halt", "Alternate Half Widths"},
            {"hist", "Historical Forms"},
            {"hkna", "Horizontal Kana Alternates"},
            {"hlig", "Historical Ligatures"},
            {"hngl", "Hangul"},
            {"hojo", "Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)"},
            {"hwid", "Half Widths"},
            {"init", "Initial Forms"},
            {"isol", "Isolated Forms"},
            {"ital", "Italics"},
            {"jalt", "Justification Alternates"},
            {"jp78", "JIS78 Forms"},
            {"jp83", "JIS83 Forms"},
            {"jp90", "JIS90 Forms"},
            {"jp04", "JIS2004 Forms"},
            {"kern", "Kerning"},
            {"lfbd", "Left Bounds"},
            {"liga", "Standard Ligatures"},
            {"ljmo", "Leading Jamo Forms"},
            {"lnum", "Lining Figures"},
            {"locl", "Localized Forms"},
            {"ltra", "Left-to-right alternates"},
            {"ltrm", "Left-to-right mirrored forms"},
            {"mark", "Mark Positioning"},
            {"med2", "Medial Forms #2"},
            {"medi", "Medial Forms"},
            {"mgrk", "Mathematical Greek"},
            {"mkmk", "Mark to Mark Positioning"},
            {"mset", "Mark Positioning via Substitution"},
            {"nalt", "Alternate Annotation Forms"},
            {"nlck", "NLC Kanji Forms"},
            {"nukt", "Nukta Forms"},
            {"numr", "Numerators"},
            {"onum", "Oldstyle Figures"},
            {"opbd", "Optical Bounds"},
            {"ordn", "Ordinals"},
            {"ornm", "Ornaments"},
            {"palt", "Proportional Alternate Widths"},
            {"pcap", "Petite Capitals"},
            {"pkna", "Proportional Kana"},
            {"pnum", "Proportional Figures"},
            {"pref", "Pre-Base Forms"},
            {"pres", "Pre-base Substitutions"},
            {"pstf", "Post-base Forms"},
            {"psts", "Post-base Substitutions"},
            {"pwid", "Proportional Widths"},
            {"qwid", "Quarter Widths"},
            {"rand", "Randomize"},
            {"rkrf", "Rakar Forms"},
            {"rlig", "Required Ligatures"},
            {"rphf", "Reph Forms"},
            {"rtbd", "Right Bounds"},
            {"rtla", "Right-to-left alternates"},
            {"rtlm", "Right-to-left mirrored forms"},
            {"ruby", "Ruby Notation Forms"},
            {"salt", "Stylistic Alternates"},
            {"sinf", "Scientific Inferiors"},
            {"size", "Optical size"},
            {"smcp", "Small Capitals"},
            {"smpl", "Simplified Forms"},
            {"ss01", "Stylistic Set 1"},
            {"ss02", "Stylistic Set 2"},
            {"ss03", "Stylistic Set 3"},
            {"ss04", "Stylistic Set 4"},
            {"ss05", "Stylistic Set 5"},
            {"ss06", "Stylistic Set 6"},
            {"ss07", "Stylistic Set 7"},
            {"ss08", "Stylistic Set 8"},
            {"ss09", "Stylistic Set 9"},
            {"ss10", "Stylistic Set 10"},
            {"ss11", "Stylistic Set 11"},
            {"ss12", "Stylistic Set 12"},
            {"ss13", "Stylistic Set 13"},
            {"ss14", "Stylistic Set 14"},
            {"ss15", "Stylistic Set 15"},
            {"ss16", "Stylistic Set 16"},
            {"ss17", "Stylistic Set 17"},
            {"ss18", "Stylistic Set 18"},
            {"ss19", "Stylistic Set 19"},
            {"ss20", "Stylistic Set 20"},
            {"subs", "Subscript"},
            {"sups", "Superscript"},
            {"swsh", "Swash"},
            {"titl", "Titling"},
            {"tjmo", "Trailing Jamo Forms"},
            {"tnam", "Traditional Name Forms"},
            {"tnum", "Tabular Figures"},
            {"trad", "Traditional Forms"},
            {"twid", "Third Widths"},
            {"unic", "Unicase"},
            {"valt", "Alternate Vertical Metrics"},
            {"vatu", "Vattu Variants"},
            {"vert", "Vertical Writing"},
            {"vhal", "Alternate Vertical Half Metrics"},
            {"vjmo", "Vowel Jamo Forms"},
            {"vkna", "Vertical Kana Alternates"},
            {"vkrn", "Vertical Kerning"},
            {"vpal", "Proportional Alternate Vertical Metrics"},
            {"vrt2", "Vertical Alternates and Rotation"},
            {"zero", "Slashed Zero"},
        };
        return findTagName(map, feature, true);
    }
}
