if (FRIBIDI_INCLUDE_DIR AND FRIBIDI_LIBRARY)
  set(FRIBIDI_FOUND TRUE)
else (FRIBIDI_INCLUDE_DIR AND FRIBIDI_LIBRARY)
  find_path(FRIBIDI_INCLUDE_DIR fribidi/fribidi.h)
  find_library(FRIBIDI_LIBRARY NAMES fribidi)

  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(FRIBIDI DEFAULT_MSG FRIBIDI_LIBRARY FRIBIDI_INCLUDE_DIR)

  set(FRIBIDI_LIBRARIES ${FRIBIDI_LIBRARY})
  
  mark_as_advanced(FRIBIDI_LIBRARY FRIBIDI_INCLUDE_DIR)  
endif (FRIBIDI_INCLUDE_DIR AND FRIBIDI_LIBRARY)
